spring.application.name=Employee-Management-System

#Database configuration Info
spring.datasource.url =${DB_URL}
spring.datasource.username =${DB_USERNAME}
spring.datasource.password =${DB_PASSWORD}
